/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libman;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author root
 */
public class ManageDatabase extends javax.swing.JFrame {

    /**
     * Creates new form ManageDatabase
     */
    ResultSet r=null;
    public ManageDatabase(javax.swing.JFrame arg) {
	settingsMenu = arg;
        initComponents();	
	getResult();
	next();
	//textFieldTitle.setWrapStyleWord(true);
	textFieldTitle.setCaretPosition(0);	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lAuthor = new javax.swing.JLabel();
        textFieldAuthor = new javax.swing.JTextField();
        lPublisher = new javax.swing.JLabel();
        textFieldPublisher = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lDomain = new javax.swing.JLabel();
        lManageDatabase = new javax.swing.JLabel();
        textFieldDomain = new javax.swing.JTextField();
        Separator = new javax.swing.JSeparator();
        lYear = new javax.swing.JLabel();
        lAccno = new javax.swing.JLabel();
        lPrice = new javax.swing.JLabel();
        textFieldAccno = new javax.swing.JTextField();
        textFieldYear = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        textFieldPrice = new javax.swing.JTextField();
        textFieldTitle = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lAuthor.setText("Author");

        textFieldAuthor.setPreferredSize(new java.awt.Dimension(150, 30));

        lPublisher.setText("Publisher");

        textFieldPublisher.setPreferredSize(new java.awt.Dimension(150, 30));

        btnBack.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        btnBack.setText("<");
        btnBack.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lDomain.setText("Domain");

        lManageDatabase.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lManageDatabase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lManageDatabase.setText("Manage Database");

        textFieldDomain.setPreferredSize(new java.awt.Dimension(150, 30));

        lYear.setText("Year");

        lAccno.setText("AccNo");

        lPrice.setText("Price");

        textFieldAccno.setPreferredSize(new java.awt.Dimension(150, 30));

        textFieldYear.setPreferredSize(new java.awt.Dimension(150, 30));

        title.setText("Title ");

        textFieldPrice.setPreferredSize(new java.awt.Dimension(150, 30));

        textFieldTitle.setPreferredSize(new java.awt.Dimension(150, 30));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnNext.setText(" + ");
	btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        btnPrev.setText("  -  ");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Separator)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lManageDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAccno)
                    .addComponent(title)
                    .addComponent(lAuthor)
                    .addComponent(lPublisher)
                    .addComponent(lDomain)
                    .addComponent(lYear)
                    .addComponent(lPrice))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldAccno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrev)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lManageDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAccno)
                    .addComponent(textFieldAccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrev))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(textFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAuthor)
                    .addComponent(textFieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPublisher)
                    .addComponent(textFieldPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDomain)
                    .addComponent(textFieldDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lYear)
                    .addComponent(textFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrice)
                    .addComponent(textFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
	setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        settingsMenu.setVisible(true);
    }                                        

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
	String accno, title, publisher, authors, domain, q, p;
	int year, price;
	accno = textFieldAccno.getText();
	title = textFieldTitle.getText();
	authors = textFieldAuthor.getText();
	publisher = textFieldPublisher.getText();
	year = Integer.parseInt(textFieldYear.getText());
	domain = textFieldDomain.getText();
	price = Integer.parseInt(textFieldPrice.getText());
	q = "Select * from BookDetails where accno = '%"+accno+"%'";
	ResultSet r = util.getResult("Library", q);
	try{
		if(!r.next()) {
			p = "insert into BookDetails values ('"+accno+"', '"+title+"', '"+publisher+"', '"+domain+"', '"+year+"', '"+price+"');";
			String[] author = authors.split(",");
			for(int i = 0 ; i < author.length ; i++ ) {
				String w = "insert into Author values ('"+accno+"', '"+author[i]+"');";
				util.SQLUpdate("Library", w);		
			}
			util.SQLUpdate("Library", p);
		
		} else {
			String uTitle = "update BookDetails set title = '"+title+"' where AccNo like '"+accno+"';";
			String uPublisher = "update BookDetails set publisher = '"+publisher+"' where AccNo like '"+accno+"';";
			String uDomain = "update BookDetails set domain = '"+domain+"' where AccNo like '"+accno+"';";
			String uYear = "update BookDetails set year = "+year+" where AccNo like '"+accno+"';";
			String uPrice = "update BookDetails set price = "+price+" where AccNo like '"+accno+"';";
			String[] author = authors.split(",");
			util.SQLUpdate("Library", "delete from Author where accno ='"+accno+"';");
			for(int i = 0 ; i < author.length ; i++ ) {
				String w = "insert into Author values ('"+accno+"', '"+author[i]+"');";	
				util.SQLUpdate("Library", w);	
			}
			util.SQLUpdate("Library", uTitle);
			util.SQLUpdate("Library", uPublisher);
			util.SQLUpdate("Library", uDomain);
			util.SQLUpdate("Library", uYear);
			util.SQLUpdate("Library", uPrice);
				
		}
		r.close();
		util.closecon();
	} catch (Exception e) {
		e.printStackTrace();	
	}
    }                                        

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
	next();
    } 
    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
	prev();
    }             
    public void getResult(){
	String q = "select AccNo, Title, Publisher, Price, Domain, Year from BookDetails";
	r = util.getResult("Library", q);
    }
    public void next(){
	String[] row = {null, null, null, null, null, null, null, null};
	try{
            	if(r.next()) {
                	row[0] = r.getString("AccNo");
                	row[1] = r.getString("Title");
                	String n = "select AuthorName from Author where AccNo like '"+row[0]+"';";
                	String author = getAuthor(util.getResult("Library", n));
                	row[2] = author;
                	row[3] = r.getString("Publisher") ;
                	row[4] = r.getString("Domain");
                	row[5] = r.getString("Year");
			row[6] = r.getString("Price");
                	textFieldAccno.setText(row[0]);
			textFieldTitle.setText(row[1]);
			textFieldAuthor.setText(row[2]);
			textFieldPublisher.setText(row[3]);
			textFieldDomain.setText(row[4]);
			textFieldYear.setText(row[5]);
			textFieldPrice.setText(row[6]);
			textFieldAccno.setCaretPosition(0);
			textFieldTitle.setCaretPosition(0);
			textFieldAuthor.setCaretPosition(0);
			textFieldPublisher.setCaretPosition(0);
			textFieldDomain.setCaretPosition(0);
			textFieldYear.setCaretPosition(0);
			textFieldPrice.setCaretPosition(0);
		}
        }catch(SQLException se){
            se.printStackTrace();
        }catch(Exception e){
            //Handle errors for Class.forName
            e.printStackTrace();
        }
    }
    public void prev(){
	String[] row = {null, null, null, null, null, null, null, null};
	try{
            	if(r.previous()) {
                	row[0] = r.getString("AccNo");
                	row[1] = r.getString("Title");
                	String n = "select AuthorName from Author where AccNo like '"+row[0]+"';";
                	String author = getAuthor(util.getResult("Library", n));
                	row[2] = author;
                	row[3] = r.getString("Publisher") ;
                	row[4] = r.getString("Domain");
                	row[5] = r.getString("Year");
			row[6] = r.getString("Price");
                	textFieldAccno.setText(row[0]);
			textFieldTitle.setText(row[1]);
			textFieldAuthor.setText(row[2]);
			textFieldPublisher.setText(row[3]);
			textFieldDomain.setText(row[4]);
			textFieldYear.setText(row[5]);
			textFieldPrice.setText(row[6]);
			textFieldAccno.setCaretPosition(0);
			textFieldTitle.setCaretPosition(0);
			textFieldAuthor.setCaretPosition(0);
			textFieldPublisher.setCaretPosition(0);
			textFieldDomain.setCaretPosition(0);
			textFieldYear.setCaretPosition(0);
			textFieldPrice.setCaretPosition(0);
        	}	
	}catch(SQLException se){
            se.printStackTrace();
        }catch(Exception e){
            //Handle errors for Class.forName
            e.printStackTrace();
        }
    }                           

    private String getAuthor(ResultSet rs){
        String authors="";
        try{
            while(rs.next()){
                if(authors != "")
                    authors += ", ";
                authors += rs.getString("AuthorName");
            }
	    rs.close();
	    util.closecon();
        }catch(SQLException se){
            se.printStackTrace();
        }catch(Exception e){
            //Handle errors for Class.forName
            e.printStackTrace();
        }
        return authors;  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(javax.swing.JFrame arg) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
		util.setLookAndFeel();
	} catch (Exception e) {
		e.printStackTrace();			
	}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDatabase(arg).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JLabel lManageDatabase;
    private javax.swing.JLabel lAccno;
    private javax.swing.JLabel title;
    private javax.swing.JLabel lAuthor;
    private javax.swing.JLabel lPublisher;
    private javax.swing.JLabel lDomain;
    private javax.swing.JLabel lYear;
    private javax.swing.JLabel lPrice;
    private javax.swing.JSeparator Separator;
    private javax.swing.JTextField textFieldAccno;
    private javax.swing.JTextField textFieldTitle;
    private javax.swing.JTextField textFieldAuthor;
    private javax.swing.JTextField textFieldPublisher;
    private javax.swing.JTextField textFieldDomain;
    private javax.swing.JTextField textFieldYear;
    private javax.swing.JTextField textFieldPrice;
    private javax.swing.JFrame settingsMenu;
    // End of variables declaration                   
}

